<?php

namespace ContainerWugnNve;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisplayCSVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DisplayCSV' shared autowired service.
     *
     * @return \App\Command\DisplayCSV
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DisplayCSV.php';

        $container->privates['App\\Command\\DisplayCSV'] = $instance = new \App\Command\DisplayCSV(\dirname(__DIR__, 4));

        $instance->setName('app:display-csv');

        return $instance;
    }
}
