<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWugnNve\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWugnNve/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWugnNve.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWugnNve\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWugnNve\App_KernelDevDebugContainer([
    'container.build_hash' => 'WugnNve',
    'container.build_id' => '5efa1d0c',
    'container.build_time' => 1676995670,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWugnNve');
